/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
  kotlin("jvm") version "1.8.22"
  id("io.ktor.plugin") version "2.3.1"
}


repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.0")
  implementation("io.opentelemetry:opentelemetry-api:1.27.0")
  implementation("io.opentelemetry:opentelemetry-sdk:1.27.0")
  implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.27.0")
  implementation("io.opentelemetry:opentelemetry-semconv:1.27.0-alpha")
  // This dependency is used by the application.
  implementation("com.google.guava:guava:31.0.1-jre")
  implementation("com.newrelic.telemetry:telemetry-core:0.15.0")
  implementation("com.newrelic.telemetry:telemetry-http-okhttp:0.15.0")
  // Use the Kotlin test library.
  testImplementation("org.jetbrains.kotlin:kotlin-test")

  // Use the Kotlin JUnit integration.
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

version = "0.0.1"

application {
  mainClass.set("sortingperformance.AppKt")
//
  applicationDefaultJvmArgs =
    listOf(
      "-javaagent:/opt/newrelic/newrelic.jar")
}